"""Unique affiliationms

Revision ID: 011c30aac055
Revises: ad16ab79dbcb
Create Date: 2023-12-31 14:53:46.508631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011c30aac055'
down_revision = 'ad16ab79dbcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux__affiliation__catalog__catalog_identifier', 'affiliation', ['catalog', 'catalog_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__affiliation__catalog__catalog_identifier', 'affiliation', type_='unique')
    # ### end Alembic commands ###
