"""Folder DOI user relevance

Revision ID: 12850d8d6eac
Revises: 6ecb4ccdbd9b
Create Date: 2024-10-14 12:05:50.153608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12850d8d6eac'
down_revision = '6ecb4ccdbd9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_doi_user_relevance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_doi_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relevant', sa.Boolean(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['folder_doi_id'], ['folder_doi.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_doi_user_relevance_folder_doi_id'), 'folder_doi_user_relevance', ['folder_doi_id'], unique=False)
    op.create_index(op.f('ix_folder_doi_user_relevance_user_id'), 'folder_doi_user_relevance', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folder_doi_user_relevance_user_id'), table_name='folder_doi_user_relevance')
    op.drop_index(op.f('ix_folder_doi_user_relevance_folder_doi_id'), table_name='folder_doi_user_relevance')
    op.drop_table('folder_doi_user_relevance')
    # ### end Alembic commands ###
