"""Source affiliations

Revision ID: 148271d4650e
Revises: d64256f8432a
Create Date: 2023-12-21 10:29:50.876516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148271d4650e'
down_revision = 'd64256f8432a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources__affiliations',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliation.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'affiliation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sources__affiliations')
    # ### end Alembic commands ###
