"""Unicode vancouver

Revision ID: 159d98e80121
Revises: 1e24ef573965
Create Date: 2024-01-11 15:32:33.702667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '159d98e80121'
down_revision = '1e24ef573965'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'keyword',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1000),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'keyword',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=1000),
               nullable=True)
    # ### end Alembic commands ###
