"""Unique subtype names

Revision ID: 17335f8986b7
Revises: beadac9a9b6a
Create Date: 2023-12-31 09:53:16.501277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17335f8986b7'
down_revision = 'beadac9a9b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subtype', 'code',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('subtype', 'description',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=False)
    op.create_unique_constraint('ux__subtype__description', 'subtype', ['description'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__subtype__description', 'subtype', type_='unique')
    op.alter_column('subtype', 'description',
               existing_type=mysql.VARCHAR(length=10000),
               nullable=True)
    op.alter_column('subtype', 'code',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
