"""Publication preprint

Revision ID: 176ea71440a6
Revises: 9dd20d6592ef
Create Date: 2024-03-11 15:51:51.222003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176ea71440a6'
down_revision = '9dd20d6592ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('preprint', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'preprint')
    # ### end Alembic commands ###
