"""Academic Groups

Revision ID: 19699919a91b
Revises: aa02911b50af
Create Date: 2024-10-22 14:42:59.145321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19699919a91b'
down_revision = 'aa02911b50af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'owner_id', name='ux__group__name__owner_id')
    )
    op.create_index(op.f('ix_group_owner_id'), 'group', ['owner_id'], unique=False)
    op.create_table('groups__academics',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('academic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_id'], ['academic.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'academic_id')
    )
    op.create_table('groups__shared_users',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups__shared_users')
    op.drop_table('groups__academics')
    op.drop_index(op.f('ix_group_owner_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
