"""Only include these statuses in auto filled folders

Revision ID: 1a0b3c93695b
Revises: f47a224c7675
Create Date: 2024-12-03 17:17:41.043787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0b3c93695b'
down_revision = 'f47a224c7675'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders__only_include_acknowledgement_statuses',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('nihr_acknowledgement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['nihr_acknowledgement_id'], ['nihr_acknowledgement.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'nihr_acknowledgement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folders__only_include_acknowledgement_statuses')
    # ### end Alembic commands ###
