"""CatalogPublicationsSources Affiliations

Revision ID: 1d2c83134692
Revises: e3afe041d630
Create Date: 2023-12-21 13:50:20.334981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2c83134692'
down_revision = 'e3afe041d630'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_publications_sources__affiliations',
    sa.Column('catalog_publications_sources_id', sa.Integer(), nullable=False),
    sa.Column('affiliation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliation.id'], ),
    sa.ForeignKeyConstraint(['catalog_publications_sources_id'], ['catalog_publications_sources.id'], ),
    sa.PrimaryKeyConstraint('catalog_publications_sources_id', 'affiliation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_publications_sources__affiliations')
    # ### end Alembic commands ###
