"""Source catalog

Revision ID: 1f33e3c78f77
Revises: 738ce123c298
Create Date: 2023-11-27 16:08:46.875189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f33e3c78f77'
down_revision = '738ce123c298'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('catalog', sa.String(length=100), nullable=False))
    op.add_column('source', sa.Column('catalog_identifier', sa.String(length=500), nullable=False))
    op.create_index(op.f('ix_source_catalog'), 'source', ['catalog'], unique=False)
    op.create_index(op.f('ix_source_catalog_identifier'), 'source', ['catalog_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_catalog_identifier'), table_name='source')
    op.drop_index(op.f('ix_source_catalog'), table_name='source')
    op.drop_column('source', 'catalog_identifier')
    op.drop_column('source', 'catalog')
    # ### end Alembic commands ###
