"""Some subtype shenanigans

Revision ID: 28a9567f3c34
Revises: 17335f8986b7
Create Date: 2023-12-31 14:46:35.238081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a9567f3c34'
down_revision = '17335f8986b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
