"""Unique sponsor names

Revision ID: 32b32142f5ae
Revises: 3aac94edc516
Create Date: 2023-12-31 08:57:22.513338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32b32142f5ae'
down_revision = '3aac94edc516'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsor', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint('ux__sponsor__name', 'sponsor', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__sponsor__name', 'sponsor', type_='unique')
    op.alter_column('sponsor', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
