"""Supplementary authors

Revision ID: 35671ea40af2
Revises: 166739c32936
Create Date: 2024-06-21 15:37:52.902880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35671ea40af2'
down_revision = '166739c32936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplementary_authors',
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('academic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academic_id'], ['academic.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('publication_id', 'academic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplementary_authors')
    # ### end Alembic commands ###
