"""Raw Data table

Revision ID: 39e412dcf994
Revises: bb1c87fa8a83
Create Date: 2024-06-28 13:23:42.361267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39e412dcf994'
down_revision = 'bb1c87fa8a83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.String(length=100), nullable=False),
    sa.Column('catalog_identifier', sa.String(length=500), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('raw_text', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    # ### end Alembic commands ###
