"""Unique  keywords

Revision ID: 3aac94edc516
Revises: cfbda1579583
Create Date: 2023-12-31 08:55:27.266763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3aac94edc516'
down_revision = 'cfbda1579583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keyword', 'keyword',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    op.create_unique_constraint('ux__keyword__keyword', 'keyword', ['keyword'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__keyword__keyword', 'keyword', type_='unique')
    op.alter_column('keyword', 'keyword',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###
