"""DOI on publication

Revision ID: 3eac4a9cf3d4
Revises: 4a610ddc4263
Create Date: 2024-01-25 15:01:51.853492

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3eac4a9cf3d4'
down_revision = '4a610ddc4263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('academic_ibfk_1', 'academic', type_='foreignkey')
    op.drop_column('academic', 'theme_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic', sa.Column('theme_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('academic_ibfk_1', 'academic', 'theme', ['theme_id'], ['id'])
    # ### end Alembic commands ###
