"""catalog publication keywords

Revision ID: 434315dd1c6a
Revises: a14cf059bc9d
Create Date: 2023-12-30 12:34:26.942511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '434315dd1c6a'
down_revision = 'a14cf059bc9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_publication__keyword',
    sa.Column('catalog_publication_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_publication_id'], ['catalog_publication.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('catalog_publication_id', 'keyword_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalog_publication__keyword')
    # ### end Alembic commands ###
