"""Unique sources

Revision ID: 466a233eb040
Revises: 28a9567f3c34
Create Date: 2023-12-31 14:47:31.271170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466a233eb040'
down_revision = '28a9567f3c34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux__source__catalog__catalog_identifier', 'source', ['catalog', 'catalog_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__source__catalog__catalog_identifier', 'source', type_='unique')
    # ### end Alembic commands ###
