"""Affiliation is industry

Revision ID: 4a610ddc4263
Revises: 159d98e80121
Create Date: 2024-01-15 11:07:33.654512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a610ddc4263'
down_revision = '159d98e80121'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('industry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliation', 'industry')
    # ### end Alembic commands ###
