"""Refresh Publication

Revision ID: 4ded1bae264e
Revises: d5acddf5d730
Create Date: 2024-01-26 15:44:10.396848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ded1bae264e'
down_revision = 'd5acddf5d730'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('refresh_full_details', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'refresh_full_details')
    # ### end Alembic commands ###
