"""Strict acknowledgement scoring

Revision ID: 4e3e5d10166c
Revises: 1a0b3c93695b
Create Date: 2025-01-23 07:36:57.310171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3e5d10166c'
down_revision = '1a0b3c93695b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('strict_nihr_acknowledgement_match', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'strict_nihr_acknowledgement_match')
    # ### end Alembic commands ###
