"""AsyncJob add last executed

Revision ID: 51ad920ed01c
Revises: cf64cb9bc810
Create Date: 2024-09-11 10:40:01.949770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51ad920ed01c'
down_revision = 'cf64cb9bc810'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('async_job', sa.Column('last_executed', sa.DateTime(), nullable=True))
    op.alter_column('async_job', 'scheduled',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('async_job', 'scheduled',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('async_job', 'last_executed')
    # ### end Alembic commands ###
