"""Remove unused tables

Revision ID: 52b8e5c4c768
Revises: 9dc96758a6aa
Create Date: 2023-11-23 16:19:27.355911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52b8e5c4c768'
down_revision = '9dc96758a6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scopus_publication')
    op.drop_table('sources__publications')
    op.drop_table('sponsors__scopus_publications')
    op.drop_table('folders__scopus_publications')
    op.drop_table('scopus_publication__keyword')
    op.drop_table('publication_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_source',
    sa.Column('publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ordinal', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['scopus_publication.id'], name='publication_source_ibfk_1'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='publication_source_ibfk_2'),
    sa.PrimaryKeyConstraint('publication_id', 'source_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scopus_publication__keyword',
    sa.Column('scopus_publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('keyword_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], name='scopus_publication__keyword_ibfk_2'),
    sa.ForeignKeyConstraint(['scopus_publication_id'], ['scopus_publication.id'], name='scopus_publication__keyword_ibfk_1'),
    sa.PrimaryKeyConstraint('scopus_publication_id', 'keyword_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('folders__scopus_publications',
    sa.Column('folder_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scopus_publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], name='folders__scopus_publications_ibfk_1'),
    sa.ForeignKeyConstraint(['scopus_publication_id'], ['scopus_publication.id'], name='folders__scopus_publications_ibfk_2'),
    sa.PrimaryKeyConstraint('folder_id', 'scopus_publication_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sponsors__scopus_publications',
    sa.Column('sponsor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scopus_publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scopus_publication_id'], ['scopus_publication.id'], name='sponsors__scopus_publications_ibfk_2'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsor.id'], name='sponsors__scopus_publications_ibfk_1'),
    sa.PrimaryKeyConstraint('sponsor_id', 'scopus_publication_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sources__publications',
    sa.Column('source_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('scopus_publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scopus_publication_id'], ['scopus_publication.id'], name='sources__publications_ibfk_1'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], name='sources__publications_ibfk_2'),
    sa.PrimaryKeyConstraint('source_id', 'scopus_publication_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scopus_publication',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('scopus_id', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('doi', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('publication_cover_date', sa.DATE(), nullable=True),
    sa.Column('pubmed_id', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('pii', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('abstract', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('author_list', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('volume', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('issue', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('pages', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('funding_text', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('is_open_access', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('cited_by_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('href', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('validation_historic', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('auto_nihr_acknowledgement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('auto_nihr_funded_open_access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nihr_acknowledgement_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('nihr_funded_open_access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('journal_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subtype_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_update_date', mysql.DATETIME(), nullable=False),
    sa.Column('created_date', mysql.DATETIME(), nullable=False),
    sa.Column('last_update_by', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('created_by', mysql.VARCHAR(length=200), nullable=False),
    sa.ForeignKeyConstraint(['auto_nihr_acknowledgement_id'], ['nihr_acknowledgement.id'], name='scopus_publication_ibfk_1'),
    sa.ForeignKeyConstraint(['auto_nihr_funded_open_access_id'], ['nihr_funded_open_access.id'], name='scopus_publication_ibfk_2'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name='scopus_publication_ibfk_5'),
    sa.ForeignKeyConstraint(['nihr_acknowledgement_id'], ['nihr_acknowledgement.id'], name='scopus_publication_ibfk_3'),
    sa.ForeignKeyConstraint(['nihr_funded_open_access_id'], ['nihr_funded_open_access.id'], name='scopus_publication_ibfk_4'),
    sa.ForeignKeyConstraint(['subtype_id'], ['subtype.id'], name='scopus_publication_ibfk_6'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
