"""Save Raw text for affiliation

Revision ID: 54201a556dff
Revises: ce0b1cab2a53
Create Date: 2024-06-28 11:18:07.980116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54201a556dff'
down_revision = 'ce0b1cab2a53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('raw_text', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliation', 'raw_text')
    # ### end Alembic commands ###
