"""Unique CatalogPublication

Revision ID: 5c4ba372aa0d
Revises: 77546f4402b6
Create Date: 2023-12-31 15:00:40.302557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4ba372aa0d'
down_revision = '77546f4402b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux__CatalogPublication__catalog__catalog_identifier', 'catalog_publication', ['catalog', 'catalog_identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__CatalogPublication__catalog__catalog_identifier', 'catalog_publication', type_='unique')
    # ### end Alembic commands ###
