"""Vancouver

Revision ID: 6cd98255a37d
Revises: ac2f5554a3f8
Create Date: 2023-12-20 17:39:59.213057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cd98255a37d'
down_revision = 'ac2f5554a3f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_publication', 'is_main')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publication', sa.Column('is_main', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
