"""DOI on publication

Revision ID: 6ea71c5898ca
Revises: 3eac4a9cf3d4
Create Date: 2024-01-25 15:12:55.983325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea71c5898ca'
down_revision = '3eac4a9cf3d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('doi', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_publication_doi'), 'publication', ['doi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_doi'), table_name='publication')
    op.drop_column('publication', 'doi')
    # ### end Alembic commands ###
