"""Publication fresh flag

Revision ID: 70742d9e4f66
Revises: ee3e3329acc9
Create Date: 2023-12-14 15:10:43.219634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70742d9e4f66'
down_revision = 'ee3e3329acc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publication', sa.Column('refresh_full_details', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_publication', 'refresh_full_details')
    # ### end Alembic commands ###
