"""Academic initials

Revision ID: 70af63ce7191
Revises: e69230350289
Create Date: 2024-04-25 16:49:18.575437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70af63ce7191'
down_revision = 'e69230350289'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic', sa.Column('initials', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic', 'initials')
    # ### end Alembic commands ###
