"""Allow authors access to folder

Revision ID: 7113b325494f
Revises: f57edd9ca1f4
Create Date: 2024-11-13 09:13:46.284617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7113b325494f'
down_revision = 'f57edd9ca1f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('author_access', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'author_access')
    # ### end Alembic commands ###
