"""Remove open access status

Revision ID: 738ce123c298
Revises: dc84a5dcfe90
Create Date: 2023-11-27 15:52:12.463848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '738ce123c298'
down_revision = 'dc84a5dcfe90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('publication_ibfk_1', 'publication', type_='foreignkey')
    op.drop_constraint('publication_ibfk_3', 'publication', type_='foreignkey')
    op.drop_column('publication', 'nihr_funded_open_access_id')
    op.drop_column('publication', 'auto_nihr_funded_open_access_id')
    op.drop_table('nihr_funded_open_access')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nihr_funded_open_access',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.add_column('publication', sa.Column('auto_nihr_funded_open_access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('publication', sa.Column('nihr_funded_open_access_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('publication_ibfk_3', 'publication', 'nihr_funded_open_access', ['nihr_funded_open_access_id'], ['id'])
    op.create_foreign_key('publication_ibfk_1', 'publication', 'nihr_funded_open_access', ['auto_nihr_funded_open_access_id'], ['id'])
    # ### end Alembic commands ###
