"""Save Raw text for publications

Revision ID: 761a0b5f0724
Revises: 35671ea40af2
Create Date: 2024-06-28 11:15:48.149703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761a0b5f0724'
down_revision = '35671ea40af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publication', sa.Column('raw_text', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_publication', 'raw_text')
    # ### end Alembic commands ###
