"""Unique folder

Revision ID: 77546f4402b6
Revises: aece9b9dfc61
Create Date: 2023-12-31 14:58:42.903441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77546f4402b6'
down_revision = 'aece9b9dfc61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux__folder__name__owner_id', 'folder', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__folder__name__owner_id', 'folder', type_='unique')
    # ### end Alembic commands ###
