"""Publication correct foreign key

Revision ID: 7e983b19e019
Revises: d12c20d56769
Create Date: 2023-11-13 16:32:37.255774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e983b19e019'
down_revision = 'd12c20d56769'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('catalog_publication_ibfk_2', 'catalog_publication', type_='foreignkey')
    # op.create_foreign_key(None, 'catalog_publication', 'publication', ['publication_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_publication', type_='foreignkey')
    op.create_foreign_key('catalog_publication_ibfk_2', 'catalog_publication', 'source', ['publication_id'], ['id'])
    # ### end Alembic commands ###
