"""Home Institution

Revision ID: 8833b59b8559
Revises: 4ded1bae264e
Create Date: 2024-02-01 10:43:47.219401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8833b59b8559'
down_revision = '4ded1bae264e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('home_institution', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'home_institution')
    # ### end Alembic commands ###
