"""Remove Soft delete for folderdoi

Revision ID: 945793c3df0d
Revises: f45f84d6ee74
Create Date: 2024-11-18 09:43:58.884002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '945793c3df0d'
down_revision = 'f45f84d6ee74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder_doi', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder_doi', sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
