"""CatalogPublicationsSources fix foreign key to catalogpublication

Revision ID: 9504ec8490b7
Revises: 1d2c83134692
Create Date: 2023-12-22 16:58:42.588531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9504ec8490b7'
down_revision = '1d2c83134692'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publications_sources', sa.Column('catalog_publication_id', sa.Integer(), nullable=False))
    op.drop_constraint('catalog_publications_sources_ibfk_1', 'catalog_publications_sources', type_='foreignkey')
    op.drop_index('ix_catalog_publications_sources_publication_id', table_name='catalog_publications_sources')
    op.create_index(op.f('ix_catalog_publications_sources_catalog_publication_id'), 'catalog_publications_sources', ['catalog_publication_id'], unique=False)
    op.create_foreign_key(None, 'catalog_publications_sources', 'catalog_publication', ['catalog_publication_id'], ['id'])
    op.drop_column('catalog_publications_sources', 'publication_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publications_sources', sa.Column('publication_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'catalog_publications_sources', type_='foreignkey')
    op.create_foreign_key('catalog_publications_sources_ibfk_1', 'catalog_publications_sources', 'publication', ['publication_id'], ['id'])
    op.drop_index(op.f('ix_catalog_publications_sources_catalog_publication_id'), table_name='catalog_publications_sources')
    op.create_index('ix_catalog_publications_sources_publication_id', 'catalog_publications_sources', ['publication_id'], unique=False)
    op.drop_column('catalog_publications_sources', 'catalog_publication_id')
    # ### end Alembic commands ###
