"""Journal preprint servers

Revision ID: 9dd20d6592ef
Revises: f134d0ef3970
Create Date: 2024-03-11 15:49:22.932862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd20d6592ef'
down_revision = 'f134d0ef3970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('preprint', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'preprint')
    # ### end Alembic commands ###
