"""Academic link to user

Revision ID: aa02911b50af
Revises: 12850d8d6eac
Create Date: 2024-10-18 13:48:59.915773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa02911b50af'
down_revision = '12850d8d6eac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_academic_user_id'), 'academic', ['user_id'], unique=False)
    op.create_foreign_key(None, 'academic', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'academic', type_='foreignkey')
    op.drop_index(op.f('ix_academic_user_id'), table_name='academic')
    op.drop_column('academic', 'user_id')
    # ### end Alembic commands ###
