"""Unique themes

Revision ID: ad16ab79dbcb
Revises: 466a233eb040
Create Date: 2023-12-31 14:52:18.990470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad16ab79dbcb'
down_revision = '466a233eb040'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ux__theme__name', 'theme', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__theme__name', 'theme', type_='unique')
    # ### end Alembic commands ###
