"""FolderDoi

Revision ID: b24ac8b69166
Revises: 70af63ce7191
Create Date: 2024-05-09 13:32:04.008539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24ac8b69166'
down_revision = '70af63ce7191'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_doi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Unicode(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(index_name='ix_folder_doi__folder_id', table_name='folder_doi', columns=('folder_id',))
    op.create_foreign_key('fk_folder_doi__folder', 'folder_doi', 'folder', ('folder_id', ), ('id', ))
    # sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_doi')
    # ### end Alembic commands ###
