"""Remove source raw data

Revision ID: b59b5f9999df
Revises: 6c555d43e526
Create Date: 2024-06-28 13:26:13.187722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b59b5f9999df'
down_revision = '6c555d43e526'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('raw_text', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
