"""Publicationnot primary keys

Revision ID: b78e12c9306f
Revises: d73e7a883257
Create Date: 2023-11-13 16:43:44.037129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b78e12c9306f'
down_revision = 'd73e7a883257'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_publication', 'journal_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('catalog_publication', 'subtype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_publication', 'subtype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('catalog_publication', 'journal_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
