"""Add excluded DOIs from folders

Revision ID: b8c6e04fab72
Revises: 945793c3df0d
Create Date: 2024-11-18 09:47:47.422392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c6e04fab72'
down_revision = '945793c3df0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_excluded_doi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Unicode(length=1000), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('last_update_by', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folder_excluded_doi_folder_id'), 'folder_excluded_doi', ['folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folder_excluded_doi_folder_id'), table_name='folder_excluded_doi')
    op.drop_table('folder_excluded_doi')
    # ### end Alembic commands ###
