"""Folder excluded acknowledgement statuses

Revision ID: ba7a01f22396
Revises: b8c6e04fab72
Create Date: 2024-12-02 11:43:24.219206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba7a01f22396'
down_revision = 'b8c6e04fab72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders__excluded_acknowledgement_statuses',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('nihr_acknowledgement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['nihr_acknowledgement_id'], ['nihr_acknowledgement.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'nihr_acknowledgement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folders__excluded_acknowledgement_statuses')
    # ### end Alembic commands ###
