"""Remove institution raw data

Revision ID: bbcc2547b34f
Revises: 39e412dcf994
Create Date: 2024-06-28 13:24:53.670119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbcc2547b34f'
down_revision = '39e412dcf994'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institution', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institution', sa.Column('raw_text', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
