"""Remove unique name of institution

Revision ID: bd62f7f1b3f6
Revises: 8833b59b8559
Create Date: 2024-02-05 09:59:21.564856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd62f7f1b3f6'
down_revision = '8833b59b8559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux__institution__name', table_name='institution')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux__institution__name', 'institution', ['name'], unique=False)
    # ### end Alembic commands ###
