"""Unique journal names

Revision ID: beadac9a9b6a
Revises: 32b32142f5ae
Create Date: 2023-12-31 09:45:49.997146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beadac9a9b6a'
down_revision = '32b32142f5ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint('ux__journal__name', 'journal', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ux__journal__name', 'journal', type_='unique')
    op.alter_column('journal', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
