"""Remove catalog publication raw data

Revision ID: cc3555966bfa
Revises: b59b5f9999df
Create Date: 2024-06-28 13:26:54.333408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc3555966bfa'
down_revision = 'b59b5f9999df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_publication', 'raw_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_publication', sa.Column('raw_text', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
