"""Remove source affiliation

Revision ID: cde2bcd18d09
Revises: d99d3bcb6300
Create Date: 2023-12-30 12:04:26.325014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cde2bcd18d09'
down_revision = 'd99d3bcb6300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_ibfk_2', 'source', type_='foreignkey')
    op.drop_column('source', 'affiliation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('affiliation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('source_ibfk_2', 'source', 'affiliation', ['affiliation_id'], ['id'])
    # ### end Alembic commands ###
