"""Save Raw text for source

Revision ID: ce0b1cab2a53
Revises: 761a0b5f0724
Create Date: 2024-06-28 11:17:36.467108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0b1cab2a53'
down_revision = '761a0b5f0724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('raw_text', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'raw_text')
    # ### end Alembic commands ###
