"""AsyncJob

Revision ID: cf64cb9bc810
Revises: d58da4207327
Create Date: 2024-09-03 13:00:53.374226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf64cb9bc810'
down_revision = 'd58da4207327'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('async_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_id_string', sa.String(length=255), nullable=True),
    sa.Column('scheduled', sa.DateTime(), nullable=False),
    sa.Column('error', sa.UnicodeText(), nullable=True),
    sa.Column('retry', sa.Boolean(), nullable=False),
    sa.Column('retry_timedelta_period', sa.String(length=10), nullable=True),
    sa.Column('retry_timedelta_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_type', 'entity_id', 'entity_id_string', name='ux__async_job__job_type__entity')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('async_job')
    # ### end Alembic commands ###
