"""Publication not in primary key

Revision ID: d12c20d56769
Revises: 91ec8660a37e
Create Date: 2023-11-13 16:20:03.030357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd12c20d56769'
down_revision = '91ec8660a37e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'validation_historic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('publication', 'auto_nihr_acknowledgement_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('publication', 'auto_nihr_funded_open_access_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('publication', 'nihr_acknowledgement_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('publication', 'nihr_funded_open_access_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('publication', 'nihr_funded_open_access_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('publication', 'nihr_acknowledgement_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('publication', 'auto_nihr_funded_open_access_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('publication', 'auto_nihr_acknowledgement_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('publication', 'validation_historic',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
