"""Institutions

Revision ID: d5acddf5d730
Revises: 6ea71c5898ca
Create Date: 2024-01-26 14:41:11.539693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5acddf5d730'
down_revision = '6ea71c5898ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog', sa.String(length=100), nullable=False),
    sa.Column('catalog_identifier', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('refresh_full_details', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalog', 'catalog_identifier', name='ux__institution__catalog__catalog_identifier'),
    sa.UniqueConstraint('name', name='ux__institution__name')
    )
    op.create_index(op.f('ix_institution_sector'), 'institution', ['sector'], unique=False)
    op.create_table('institutions__publications',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('institution_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institutions__publications')
    op.drop_index(op.f('ix_institution_sector'), table_name='institution')
    op.drop_table('institution')
    # ### end Alembic commands ###
