"""Publication nullable columns

Revision ID: d73e7a883257
Revises: 7e983b19e019
Create Date: 2023-11-13 16:38:31.062409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd73e7a883257'
down_revision = '7e983b19e019'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_publication', 'is_open_access',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('catalog_publication', 'cited_by_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalog_publication', 'cited_by_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('catalog_publication', 'is_open_access',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
