"""Refresh affiliations

Revision ID: d99d3bcb6300
Revises: 7defdd4d102b
Create Date: 2023-12-30 10:25:43.134888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99d3bcb6300'
down_revision = '7defdd4d102b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('refresh_details', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliation', 'refresh_details')
    # ### end Alembic commands ###
