"""CatalogPublicationsSources primary key

Revision ID: e3afe041d630
Revises: f083622210a6
Create Date: 2023-12-21 13:47:45.063558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3afe041d630'
down_revision = 'f083622210a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_catalog_publications_sources_publication_id'), 'catalog_publications_sources', ['publication_id'], unique=False)
    op.create_index(op.f('ix_catalog_publications_sources_source_id'), 'catalog_publications_sources', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalog_publications_sources_source_id'), table_name='catalog_publications_sources')
    op.drop_index(op.f('ix_catalog_publications_sources_publication_id'), table_name='catalog_publications_sources')
    # ### end Alembic commands ###
