"""Academic Google Scholar ID

Revision ID: e69230350289
Revises: 176ea71440a6
Create Date: 2024-04-25 12:00:21.777151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69230350289'
down_revision = '176ea71440a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic', sa.Column('google_scholar_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('academic', 'google_scholar_id')
    # ### end Alembic commands ###
