"""Sponsor is industry

Revision ID: e7175e45043e
Revises: e7543648790d
Create Date: 2024-01-03 16:54:34.312614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7175e45043e'
down_revision = 'e7543648790d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor', sa.Column('industry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsor', 'industry')
    # ### end Alembic commands ###
