"""Set home organisation

Revision ID: e7543648790d
Revises: f47ccf9b0cc0
Create Date: 2024-01-03 16:49:49.781600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7543648790d'
down_revision = 'f47ccf9b0cc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('home_organisation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliation', 'home_organisation')
    # ### end Alembic commands ###
