"""Publications not BRC

Revision ID: ee3e3329acc9
Revises: 132b00d54a32
Create Date: 2023-12-07 13:15:39.598727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3e3329acc9'
down_revision = '132b00d54a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publication', sa.Column('not_brc', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'not_brc')
    # ### end Alembic commands ###
