"""Acknowledgement colour

Revision ID: f134d0ef3970
Revises: bd62f7f1b3f6
Create Date: 2024-03-04 15:56:35.586027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f134d0ef3970'
down_revision = 'bd62f7f1b3f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nihr_acknowledgement', sa.Column('colour', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nihr_acknowledgement', 'colour')
    # ### end Alembic commands ###
