"""Folder added fields

Revision ID: f57edd9ca1f4
Revises: 19699919a91b
Create Date: 2024-10-25 10:44:11.254162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f57edd9ca1f4'
down_revision = '19699919a91b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('academic', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.add_column('folder', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('folder', sa.Column('autofill_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'autofill_year')
    op.drop_column('folder', 'description')
    op.alter_column('academic', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
